version: '2'

services:

  server-app:
    build: ./server-app
    ports:
      - '3000:3000'
    volumes:
      - server-app-sync:/opt/app:rw
      - ./server-logs/:/opt/app/logs/

volumes:
  pgdata: {}
  server-app-sync:
    external: true
